export default {
  REQUEST_TRADES_START: 'REQUEST_TRADES_START',
  REQUEST_TRADES_SUCCESS: 'REQUEST_TRADES_SUCCESS',
  REQUEST_TRADES_FAILURE: 'REQUEST_TRADES_FAILURE',
  CHANGE_TRADE_ATTRIBUTE: 'CHANGE_TRADE_ATTRIBUTE',
  NEW_TRADE: 'NEW_TRADE',
  REMOVE_TRADE: 'REMOVE_TRADE',
  DELETE_TRADE_START: 'DELETE_TRADE_START',
  DELETE_TRADE_SUCCESS: 'DELETE_TRADE_SUCCESS',
  DELETE_TRADE_FAILURE: 'DELETE_TRADE_FAILURE',
  CANCEL_TRANSACTION: 'CANCEL_TRANSACTION'
}
