export default {
  REQUEST_TRADES_START: 'REQUEST_TRADES_START',
  REQUEST_TRADES_SUCCESS: 'REQUEST_TRADES_SUCCESS',
  REQUEST_TRADES_FAILURE: 'REQUEST_TRADES_FAILURE',
  CHANGE_TRADE_ATTRIBUTE: 'CHANGE_TRADE_ATTRIBUTE',
  NEW_TRADE: 'NEW_TRADE',
}
